//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitialProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InitialProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupne ture.
        /// </summary>
        public static string AvailableTours {
            get {
                return ResourceManager.GetString("AvailableTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koje su prosečne godine grupe?.
        /// </summary>
        public static string AverageAgeQuestion {
            get {
                return ResourceManager.GetString("AverageAgeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Dodati komentar:*.
        /// </summary>
        public static string CommentQuestion {
            get {
                return ResourceManager.GetString("CommentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevanje kompleksnih tura.
        /// </summary>
        public static string ComplexTourRequestingTab {
            get {
                return ResourceManager.GetString("ComplexTourRequestingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutni broj gostiju:.
        /// </summary>
        public static string CurrentGuests {
            get {
                return ResourceManager.GetString("CurrentGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string DGCity {
            get {
                return ResourceManager.GetString("DGCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string DGCountry {
            get {
                return ResourceManager.GetString("DGCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje (sati).
        /// </summary>
        public static string DGDuration {
            get {
                return ResourceManager.GetString("DGDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gostiju.
        /// </summary>
        public static string DGGuests {
            get {
                return ResourceManager.GetString("DGGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string DGLanguage {
            get {
                return ResourceManager.GetString("DGLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string DGName {
            get {
                return ResourceManager.GetString("DGName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videti još.
        /// </summary>
        public static string DGSeeMore {
            get {
                return ResourceManager.GetString("DGSeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje (sati):.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krajnji datum.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string fg {
            get {
                return ResourceManager.GetString("fg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriraj.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtracija.
        /// </summary>
        public static string Filtration {
            get {
                return ResourceManager.GetString("Filtration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtracija se koristi da se prikažu samo specifične, relevantne ture kada se unesu željene informacije..
        /// </summary>
        public static string FiltrationInfo {
            get {
                return ResourceManager.GetString("FiltrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodič:.
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slike ture:.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Dodati jednu ili više slika:*.
        /// </summary>
        public static string ImagesQuestion {
            get {
                return ResourceManager.GetString("ImagesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Koliko je tura bila zanimljiva?*.
        /// </summary>
        public static string InterestingnessQuestion {
            get {
                return ResourceManager.GetString("InterestingnessQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Kako biste ocenili vodičevo znanje?*.
        /// </summary>
        public static string KnowledgeQuestion {
            get {
                return ResourceManager.GetString("KnowledgeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži na engleskom.
        /// </summary>
        public static string LanguageBtn {
            get {
                return ResourceManager.GetString("LanguageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Kako biste ocenili vodičevo poznavanje jezika?*.
        /// </summary>
        public static string LanguageQuestion {
            get {
                return ResourceManager.GetString("LanguageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalan broj gostiju:.
        /// </summary>
        public static string MaxGuests {
            get {
                return ResourceManager.GetString("MaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sledeća.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne želim da koristim vaučer..
        /// </summary>
        public static string NoVoucher {
            get {
                return ResourceManager.GetString("NoVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gostiju:.
        /// </summary>
        public static string PersonCount {
            get {
                return ResourceManager.GetString("PersonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koliko ljudi će prisustvovati turi?.
        /// </summary>
        public static string PersonCountQuestion {
            get {
                return ResourceManager.GetString("PersonCountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodna.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi turu kako bi rezervisao!.
        /// </summary>
        public static string ReserveInfo {
            get {
                return ResourceManager.GetString("ReserveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezerviši turu.
        /// </summary>
        public static string ReserveTour {
            get {
                return ResourceManager.GetString("ReserveTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početni datum.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslati.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad ture:.
        /// </summary>
        public static string TourCity {
            get {
                return ResourceManager.GetString("TourCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država ture:.
        /// </summary>
        public static string TourCountry {
            get {
                return ResourceManager.GetString("TourCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis ture:.
        /// </summary>
        public static string TourDesc {
            get {
                return ResourceManager.GetString("TourDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv ture:.
        /// </summary>
        public static string TourName {
            get {
                return ResourceManager.GetString("TourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocenjivanje ture.
        /// </summary>
        public static string TourRatingTab {
            get {
                return ResourceManager.GetString("TourRatingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevanje tura.
        /// </summary>
        public static string TourRequestingTab {
            get {
                return ResourceManager.GetString("TourRequestingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervisanje ture.
        /// </summary>
        public static string TourReservationTab {
            get {
                return ResourceManager.GetString("TourReservationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praćenje ture.
        /// </summary>
        public static string TourTrackingTab {
            get {
                return ResourceManager.GetString("TourTrackingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veoma loše.
        /// </summary>
        public static string VeryBad {
            get {
                return ResourceManager.GetString("VeryBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veoma dobro.
        /// </summary>
        public static string VeryGood {
            get {
                return ResourceManager.GetString("VeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaučeri mogu da se iskoriste pri rezervaciji ture..
        /// </summary>
        public static string Voucher1 {
            get {
                return ResourceManager.GetString("Voucher1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaučeri se mogu osvojiti na nekoliko načina:.
        /// </summary>
        public static string Voucher2 {
            get {
                return ResourceManager.GetString("Voucher2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisustvovanjem na barem 5 tura u jednoj godini. Ovi vaučeri traju 6 meseci i mogu se koristiti za bilo koju turu..
        /// </summary>
        public static string Voucher3 {
            get {
                return ResourceManager.GetString("Voucher3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kada vodič da otkaz ili otkaže turu koju ste rezervisali..
        /// </summary>
        public static string Voucher4 {
            get {
                return ResourceManager.GetString("Voucher4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iskorišćeni ili nevažeći vaučeri se neće prikazivati..
        /// </summary>
        public static string Voucher5 {
            get {
                return ResourceManager.GetString("Voucher5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šta su vaučeri?.
        /// </summary>
        public static string Voucher6 {
            get {
                return ResourceManager.GetString("Voucher6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaučeri.
        /// </summary>
        public static string VouchersTab {
            get {
                return ResourceManager.GetString("VouchersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tvoji vaučeri.
        /// </summary>
        public static string YourVouchers {
            get {
                return ResourceManager.GetString("YourVouchers", resourceCulture);
            }
        }
    }
}
