//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitialProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InitialProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupne ture.
        /// </summary>
        public static string AvailableTours {
            get {
                return ResourceManager.GetString("AvailableTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koje su prosečne godine grupe?.
        /// </summary>
        public static string AverageAgeQuestion {
            get {
                return ResourceManager.GetString("AverageAgeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrani datumi.
        /// </summary>
        public static string ChosenDatesDG {
            get {
                return ResourceManager.GetString("ChosenDatesDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Dodati komentar:*.
        /// </summary>
        public static string CommentQuestion {
            get {
                return ResourceManager.GetString("CommentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Složene ture se sastoje od više od jedne obične ture..
        /// </summary>
        public static string ComplexTourInfo {
            get {
                return ResourceManager.GetString("ComplexTourInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled kompleksne ture.
        /// </summary>
        public static string ComplexTourOverview {
            get {
                return ResourceManager.GetString("ComplexTourOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevanje kompleksnih tura.
        /// </summary>
        public static string ComplexTourRequestingTab {
            get {
                return ResourceManager.GetString("ComplexTourRequestingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Složene ture.
        /// </summary>
        public static string ComplexTours {
            get {
                return ResourceManager.GetString("ComplexTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutni broj gostiju:.
        /// </summary>
        public static string CurrentGuests {
            get {
                return ResourceManager.GetString("CurrentGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno aktivna ključna tačka:.
        /// </summary>
        public static string CurrentlyActiveCP {
            get {
                return ResourceManager.GetString("CurrentlyActiveCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno aktivna tura:.
        /// </summary>
        public static string CurrentlyActiveTour {
            get {
                return ResourceManager.GetString("CurrentlyActiveTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string DGCity {
            get {
                return ResourceManager.GetString("DGCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string DGCountry {
            get {
                return ResourceManager.GetString("DGCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv tačke.
        /// </summary>
        public static string DGCPName {
            get {
                return ResourceManager.GetString("DGCPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje (sati).
        /// </summary>
        public static string DGDuration {
            get {
                return ResourceManager.GetString("DGDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gostiju.
        /// </summary>
        public static string DGGuests {
            get {
                return ResourceManager.GetString("DGGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodič.
        /// </summary>
        public static string DGGuide {
            get {
                return ResourceManager.GetString("DGGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string DGLanguage {
            get {
                return ResourceManager.GetString("DGLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string DGName {
            get {
                return ResourceManager.GetString("DGName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redosled.
        /// </summary>
        public static string DGOrder {
            get {
                return ResourceManager.GetString("DGOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videti još.
        /// </summary>
        public static string DGSeeMore {
            get {
                return ResourceManager.GetString("DGSeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje (sati):.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završni datumi.
        /// </summary>
        public static string EndDatesDG {
            get {
                return ResourceManager.GetString("EndDatesDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme završavanja:.
        /// </summary>
        public static string EndDateTime {
            get {
                return ResourceManager.GetString("EndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krajnji datum.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriraj.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtracija.
        /// </summary>
        public static string Filtration {
            get {
                return ResourceManager.GetString("Filtration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtracija se koristi da se prikažu samo specifične, relevantne ture kada se unesu željene informacije..
        /// </summary>
        public static string FiltrationInfo {
            get {
                return ResourceManager.GetString("FiltrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završene Ture.
        /// </summary>
        public static string FinishedTours {
            get {
                return ResourceManager.GetString("FinishedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite završenu turu kako biste ocenili..
        /// </summary>
        public static string FinishedToursInfo {
            get {
                return ResourceManager.GetString("FinishedToursInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosečan broj gostiju za odabranu godinu:.
        /// </summary>
        public static string guestStatistic {
            get {
                return ResourceManager.GetString("guestStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vodič:.
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna stranica.
        /// </summary>
        public static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slike ture:.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Dodati jednu ili više slika:*.
        /// </summary>
        public static string ImagesQuestion {
            get {
                return ResourceManager.GetString("ImagesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Koliko je tura bila zanimljiva?*.
        /// </summary>
        public static string InterestingnessQuestion {
            get {
                return ResourceManager.GetString("InterestingnessQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Kako biste ocenili vodičevo znanje?*.
        /// </summary>
        public static string KnowledgeQuestion {
            get {
                return ResourceManager.GetString("KnowledgeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži na engleskom.
        /// </summary>
        public static string LanguageBtn {
            get {
                return ResourceManager.GetString("LanguageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik jezika.
        /// </summary>
        public static string languageChart {
            get {
                return ResourceManager.GetString("languageChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Kako biste ocenili vodičevo poznavanje jezika?*.
        /// </summary>
        public static string LanguageQuestion {
            get {
                return ResourceManager.GetString("LanguageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezici.
        /// </summary>
        public static string LanguagesDG {
            get {
                return ResourceManager.GetString("LanguagesDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz broja zahteva spram jezika:.
        /// </summary>
        public static string languageStatistic {
            get {
                return ResourceManager.GetString("languageStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik lokacija.
        /// </summary>
        public static string locationChart {
            get {
                return ResourceManager.GetString("locationChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacije.
        /// </summary>
        public static string LocationsDG {
            get {
                return ResourceManager.GetString("LocationsDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz statusa zahteva spram lokacija:.
        /// </summary>
        public static string locationStatistic {
            get {
                return ResourceManager.GetString("locationStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalan broj gostiju:.
        /// </summary>
        public static string MaxGuests {
            get {
                return ResourceManager.GetString("MaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tvoji zahtevi za ture.
        /// </summary>
        public static string myTourRequests {
            get {
                return ResourceManager.GetString("myTourRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sledeća.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t requested any complex tours..
        /// </summary>
        public static string noComplexTourRequests {
            get {
                return ResourceManager.GetString("noComplexTourRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije ostalo nijedno slobodno mesto na odabranoj turi. Prikazane su dostupne ture u istom gradu:.
        /// </summary>
        public static string NoSpacesAvailable {
            get {
                return ResourceManager.GetString("NoSpacesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema nijedna trenutno aktivna tura..
        /// </summary>
        public static string NoTourActive {
            get {
                return ResourceManager.GetString("NoTourActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne želim da koristim vaučer..
        /// </summary>
        public static string NoVoucher {
            get {
                return ResourceManager.GetString("NoVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate nijedan vaučer..
        /// </summary>
        public static string NoVouchers {
            get {
                return ResourceManager.GetString("NoVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gostiju:.
        /// </summary>
        public static string PersonCount {
            get {
                return ResourceManager.GetString("PersonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koliko ljudi će prisustvovati turi?.
        /// </summary>
        public static string PersonCountQuestion {
            get {
                return ResourceManager.GetString("PersonCountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodna.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceni turu.
        /// </summary>
        public static string rateTour {
            get {
                return ResourceManager.GetString("rateTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceni turu.
        /// </summary>
        public static string RateTourBtn {
            get {
                return ResourceManager.GetString("RateTourBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevaj turu.
        /// </summary>
        public static string requestATour {
            get {
                return ResourceManager.GetString("requestATour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevaj turu.
        /// </summary>
        public static string requestATourBtn {
            get {
                return ResourceManager.GetString("requestATourBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevaj složenu turu.
        /// </summary>
        public static string requestComplexTour {
            get {
                return ResourceManager.GetString("requestComplexTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi turu kako bi rezervisao!.
        /// </summary>
        public static string ReserveInfo {
            get {
                return ResourceManager.GetString("ReserveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezerviši turu.
        /// </summary>
        public static string ReserveTour {
            get {
                return ResourceManager.GetString("ReserveTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži više.
        /// </summary>
        public static string ShowMoreBtn {
            get {
                return ResourceManager.GetString("ShowMoreBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početni datum.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početni datumi.
        /// </summary>
        public static string StartDatesDG {
            get {
                return ResourceManager.GetString("StartDatesDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početno vreme:.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusDG {
            get {
                return ResourceManager.GetString("StatusDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusi.
        /// </summary>
        public static string StatusesDG {
            get {
                return ResourceManager.GetString("StatusesDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslati.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslate ture:.
        /// </summary>
        public static string SubmittedRegularTours {
            get {
                return ResourceManager.GetString("SubmittedRegularTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokušao si da dodaš previše gostiju. Slobodno je još samo jedno mesto..
        /// </summary>
        public static string TooManyGuestsMSG1 {
            get {
                return ResourceManager.GetString("TooManyGuestsMSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokušao si da dodaš previše gostiju. Slobodno je još .
        /// </summary>
        public static string TooManyGuestsMSGMany1 {
            get {
                return ResourceManager.GetString("TooManyGuestsMSGMany1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  mesta..
        /// </summary>
        public static string TooManyGuestsMSGMany2 {
            get {
                return ResourceManager.GetString("TooManyGuestsMSGMany2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad ture:.
        /// </summary>
        public static string TourCity {
            get {
                return ResourceManager.GetString("TourCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država ture:.
        /// </summary>
        public static string TourCountry {
            get {
                return ResourceManager.GetString("TourCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis ture:.
        /// </summary>
        public static string TourDesc {
            get {
                return ResourceManager.GetString("TourDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv ture:.
        /// </summary>
        public static string TourName {
            get {
                return ResourceManager.GetString("TourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocenjivanje ture.
        /// </summary>
        public static string TourRatingTab {
            get {
                return ResourceManager.GetString("TourRatingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevanje tura.
        /// </summary>
        public static string TourRequestingTab {
            get {
                return ResourceManager.GetString("TourRequestingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervisanje ture.
        /// </summary>
        public static string TourReservationTab {
            get {
                return ResourceManager.GetString("TourReservationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praćenje ture.
        /// </summary>
        public static string TourTrackingTab {
            get {
                return ResourceManager.GetString("TourTrackingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obeležena je tačka koja je trenutno aktivna..
        /// </summary>
        public static string TrackingInfo {
            get {
                return ResourceManager.GetString("TrackingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praćenje ture.
        /// </summary>
        public static string TrackTour {
            get {
                return ResourceManager.GetString("TrackTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veoma loše.
        /// </summary>
        public static string VeryBad {
            get {
                return ResourceManager.GetString("VeryBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veoma dobro.
        /// </summary>
        public static string VeryGood {
            get {
                return ResourceManager.GetString("VeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaučeri mogu da se iskoriste pri rezervaciji ture..
        /// </summary>
        public static string Voucher1 {
            get {
                return ResourceManager.GetString("Voucher1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaučeri se mogu osvojiti na nekoliko načina:.
        /// </summary>
        public static string Voucher2 {
            get {
                return ResourceManager.GetString("Voucher2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisustvovanjem na barem 5 tura u jednoj godini. Ovi vaučeri traju 6 meseci i mogu se koristiti za bilo koju turu..
        /// </summary>
        public static string Voucher3 {
            get {
                return ResourceManager.GetString("Voucher3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kada vodič da otkaz ili otkaže turu koju ste rezervisali..
        /// </summary>
        public static string Voucher4 {
            get {
                return ResourceManager.GetString("Voucher4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iskorišćeni ili nevažeći vaučeri se neće prikazivati..
        /// </summary>
        public static string Voucher5 {
            get {
                return ResourceManager.GetString("Voucher5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šta su vaučeri?.
        /// </summary>
        public static string Voucher6 {
            get {
                return ResourceManager.GetString("Voucher6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Vaučeri mogu da se iskoriste pri rezervaciji ture.
        ///- Vaučeri se mogu osvojiti na nekoliko načina:
        ///  - Prisustvovanjem na barem 5 tura u jednoj godini.
        ///  - Kada vodič da otkaz ili otkaže turu koju ste rezervisali.
        ///- Iskorišćeni ili nevažeći vaučeri se neće prikazivati.
        /// </summary>
        public static string VoucherInfo {
            get {
                return ResourceManager.GetString("VoucherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaučeri.
        /// </summary>
        public static string VouchersTab {
            get {
                return ResourceManager.GetString("VouchersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli na DMJM Tours! Šta biste želeli da radite?.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz broja zahteva spram godine:.
        /// </summary>
        public static string yearStatistic {
            get {
                return ResourceManager.GetString("yearStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaučeri.
        /// </summary>
        public static string YourVouchers {
            get {
                return ResourceManager.GetString("YourVouchers", resourceCulture);
            }
        }
    }
}
